name: pr
on:
    pull_request
jobs:
    lint:
        name: Check that it conforms to the style guide
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Setup Toltec environment
              uses: ./.github/actions/setup
            - name: Check formatting
              run: make format
            - name: Check for erroneous constructs
              run: make lint
    pr:
        name: Check that it builds without error
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Setup Toltec environment
              uses: ./.github/actions/setup
            - name: Build packages
              run: remote_repo='https://toltec-dev.org/${{ github.base_ref }}' make repo-new
            - name: Save the build output
              uses: actions/upload-artifact@v2
              with:
                name: repo
                path: build/repo
