name: stable
on:
    push:
        branches:
            - stable
jobs:
    stable:
        name: Build and publish the stable channel
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Install missing tools
              run: |
                sudo apt-get install bsdtar tree
            - name: Build packages
              run: |
                remote_repo="https://toltec-dev.org/stable" make repo
            - name: Transfer packages and index
              run: |
                mkdir -p private
                chmod 700 private
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > private/id_rsa
                echo "${{ secrets.SSH_KNOWN_HOSTS }}" > private/known_hosts
                chmod 600 private/*
                rsync --archive --verbose --compress --delete \
                    -e "ssh -i private/id_rsa -o UserKnownHostsFile=private/known_hosts" \
                    build/repo/ "${{ secrets.REMOTE }}":/srv/toltec/stable
                scp -i private/id_rsa -o UserKnownHostsFile=private/known_hosts \
                    scripts/bootstrap/bootstrap "${{ secrets.REMOTE }}":/srv/toltec
