name: testing
on:
    push:
        branches:
            - testing
jobs:
    testing:
        name: Build and publish the testing channel
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Install missing tools
              run: |
                sudo apt-get install bsdtar tree
            - name: Build packages
              run: |
                ./scripts/repo-build package build https://toltec.delab.re/testing
            - name: Transfer packages and index
              run: |
                mkdir -p private
                chmod 700 private
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > private/id_rsa
                echo "${{ secrets.SSH_KNOWN_HOSTS }}" > private/known_hosts
                chmod 600 private/*
                rsync -avz \
                    -e "ssh -i private/id_rsa -o UserKnownHostsFile=private/known_hosts" \
                    build/repo/ "${{ secrets.REMOTE }}":/srv/toltec/testing
